/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package onlineExamSystem;

/**
 *
 * @author Qazi Hammad
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jteacher = new javax.swing.JButton();
        hstudent = new javax.swing.JButton();
        hadmin = new javax.swing.JButton();
        hexit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jteacher.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jteacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/onlineExamSystem/index admin.png"))); // NOI18N
        jteacher.setText("Teacher");
        jteacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jteacherActionPerformed(evt);
            }
        });
        getContentPane().add(jteacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 278, -1, -1));

        hstudent.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hstudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/onlineExamSystem/index student.png"))); // NOI18N
        hstudent.setText("Student");
        hstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hstudentActionPerformed(evt);
            }
        });
        getContentPane().add(hstudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, -1, -1));

        hadmin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hadmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/onlineExamSystem/index admin.png"))); // NOI18N
        hadmin.setText("Admin");
        hadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hadminActionPerformed(evt);
            }
        });
        getContentPane().add(hadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, -1, -1));

        hexit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/onlineExamSystem/Close.png"))); // NOI18N
        hexit.setText("Exit");
        hexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hexitActionPerformed(evt);
            }
        });
        getContentPane().add(hexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 280, -1, -1));

        jLabel1.setFont(new java.awt.Font("Mongolian Baiti", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Home Page");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 296, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 280, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/onlineExamSystem/index background.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hadminActionPerformed
        // TODO add your handling code here:
        dispose();
        new adminlogin().setVisible(true);
    }//GEN-LAST:event_hadminActionPerformed

    private void hstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hstudentActionPerformed
        // TODO add your handling code here:
        dispose();
        new Studentlogin().setVisible(true);
    }//GEN-LAST:event_hstudentActionPerformed

    private void hexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_hexitActionPerformed

    private void jteacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jteacherActionPerformed
        // TODO add your handling code here:
        dispose();
        new Teacherlogin().setVisible(true);
    }//GEN-LAST:event_jteacherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hadmin;
    private javax.swing.JButton hexit;
    private javax.swing.JButton hstudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jteacher;
    // End of variables declaration//GEN-END:variables
}
